module.exports = [
    {
        id: 1,
        event_name: "Doctor's Appointment",
        event_description: "Regular check-up with the physician",
        event_date: new Date("2023-08-10"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 2,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss project updates",
        event_date: new Date("2023-08-18"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 3,
        event_name: "Conference: Tech Expo",
        event_description: "Tech expo showcasing the latest innovations",
        event_date: new Date("2023-08-25"),
        event_category: "Conference",
        user_id: 1,
    },
    {
        id: 4,
        event_name: "Workshop: Photography Basics",
        event_description: "Learn the basics of photography techniques",
        event_date: new Date("2023-08-13"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 5,
        event_name: "Seminar: Time Management",
        event_description: "Seminar on effective time management skills",
        event_date: new Date("2023-08-1"),
        event_category: "Seminar",
        user_id: 1,
    },
    {
        id: 6,
        event_name: "Dentist Appointment",
        event_description: "Dental check-up and cleaning",
        event_date: new Date("2023-08-04"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 7,
        event_name: "Exhibition: Art Showcase",
        event_description: "Exhibition featuring local artists' work",
        event_date: new Date("2023-08-21"),
        event_category: "Exhibition",
        user_id: 1,
    },
    {
        id: 8,
        event_name: "Team Building Activity",
        event_description: "Outdoor team-building event",
        event_date: new Date("2023-08-17"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 9,
        event_name: "Workshop: Cooking Class",
        event_description: "Hands-on cooking class for beginners",
        event_date: new Date("2023-08-11"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 10,
        event_name: "Webinar: Marketing Trends",
        event_description: "Online webinar discussing current marketing trends",
        event_date: new Date("2023-08-30"),
        event_category: "Webinar",
        user_id: 1,
    },
    {
        id: 11,
        event_name: "Appointment with Therapist",
        event_description: "Private therapy session.",
        event_date: new Date("2023-09-02"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 12,
        event_name: "Workshop: Public Speaking",
        event_description: "Learn effective public speaking techniques",
        event_date: new Date("2023-09-07"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 13,
        event_name: "Conference: Healthcare Summit",
        event_description: "Summit discussing advancements in healthcare",
        event_date: new Date("2023-09-12"),
        event_category: "Conference",
        user_id: 1,
    },
    {
        id: 14,
        event_name: "Work Shift: Night Shift",
        event_description: "Night shift for essential maintenance",
        event_date: new Date("2023-09-14"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 15,
        event_name: "Seminar: Financial Planning",
        event_description: "Seminar on managing personal finances",
        event_date: new Date("2023-09-17"),
        event_category: "Seminar",
        user_id: 1,
    },
    {
        id: 16,
        event_name: "Dentist Appointment",
        event_description: "Dental follow-up appointment",
        event_date: new Date("2023-09-20"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 17,
        event_name: "Exhibition: Sculpture Display",
        event_description: "Exhibition showcasing local sculptors",
        event_date: new Date("2023-09-22"),
        event_category: "Exhibition",
        user_id: 1,
    },
    {
        id: 18,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to review goals",
        event_date: new Date("2023-09-24"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 19,
        event_name: "Yoga and Meditation",
        event_description: "Workshop focusing on relaxation techniques",
        event_date: new Date("2023-09-27"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 20,
        event_name: "Webinar: Digital Marketing Strategies",
        event_description: "Online webinar on effective digital marketing",
        event_date: new Date("2023-09-30"),
        event_category: "Webinar",
        user_id: 1,
    },
    {
        id: 21,
        event_name: "Workshop: Creative Writing",
        event_description: "Workshop to enhance creative writing skills",
        event_date: new Date("2023-10-05"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 22,
        event_name: "Conference: Renewable Energy Summit",
        event_description: "Summit discussing advancements in renewable energy",
        event_date: new Date("2023-10-10"),
        event_category: "Conference",
        user_id: 1,
    },
    {
        id: 23,
        event_name: "Work Shift: Morning Shift",
        event_description: "Morning shift for routine maintenance",
        event_date: new Date("2023-10-13"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 24,
        event_name: "Leadership Development",
        event_description: "Seminar on becoming an effective leader",
        event_date: new Date("2023-10-15"),
        event_category: "Seminar",
        user_id: 1,
    },
    {
        id: 25,
        event_name: "Haircut Appointment",
        event_description: "Scheduled haircut and styling",
        event_date: new Date("2023-10-18"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 26,
        event_name: "Exhibition: Photography Showcase",
        event_description: "Exhibition featuring local photographers' work",
        event_date: new Date("2023-10-20"),
        event_category: "Exhibition",
        user_id: 1,
    },
    {
        id: 27,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss progress",
        event_date: new Date("2023-10-25"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 28,
        event_name: "Workshop: Painting Techniques",
        event_description: "Workshop teaching various painting techniques",
        event_date: new Date("2023-10-28"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 29,
        event_name: "Webinar: E-Commerce Strategies",
        event_description: "Online webinar on effective e-commerce strategies",
        event_date: new Date("2023-10-30"),
        event_category: "Webinar",
        user_id: 1,
    },
    {
        id: 30,
        event_name: "Appointment: Financial Advisor",
        event_description: "Meeting with a financial advisor",
        event_date: new Date("2023-11-05"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 31,
        event_name: "Workshop: Coding Bootcamp",
        event_description: "Intensive coding bootcamp for beginners",
        event_date: new Date("2023-11-07"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 32,
        event_name: "Conference: AI and Automation Summit",
        event_description: "Summit discussing AI and automation trends",
        event_date: new Date("2023-11-11"),
        event_category: "Conference",
        user_id: 1,
    },
    {
        id: 33,
        event_name: "Work Shift: Afternoon Shift",
        event_description: "Afternoon shift for system updates",
        event_date: new Date("2023-11-12"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 34,
        event_name: "Seminar: Stress Management",
        event_description: "Seminar on coping with stress effectively",
        event_date: new Date("2023-11-15"),
        event_category: "Seminar",
        user_id: 1,
    },
    {
        id: 35,
        event_name: "Eye Check-up Appointment",
        event_description: "Routine eye check-up and prescription update",
        event_date: new Date(" 2023-11-20"),
        event_category: "Appointment",
        user_id: 1,
    },
    {
        id: 36,
        event_name: "Exhibition: Modern Art Display",
        event_description: "Exhibition featuring contemporary artists' work",
        event_date: new Date("2023-11-23"),
        event_category: "Exhibition",
        user_id: 1,
    },
    {
        id: 37,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting for project planning",
        event_date: new Date("2023-11-25"),
        event_category: "Work Shift",
        user_id: 1,
    },
    {
        id: 38,
        event_name: "Workshop: Graphic Design Basics",
        event_description: "Learn Graphic Design Basics",
        event_date: new Date("2023-11-28"),
        event_category: "Workshop",
        user_id: 1,
    },
    {
        id: 39,
        event_name: "Doctor's Appointment",
        event_description: "Regular check-up with the physician",
        event_date: new Date("2023-08-15"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 40,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss project updates",
        event_date: new Date("2023-08-20"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 41,
        event_name: "Conference: Tech Expo",
        event_description: "Tech expo showcasing the latest innovations",
        event_date: new Date("2023-08-27"),
        event_category: "Conference",
        user_id: 2,
    },
    {
        id: 42,
        event_name: "Workshop: Photography Basics",
        event_description: "Learn the basics of photography techniques",
        event_date: new Date("2023-08-10"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 43,
        event_name: "Seminar: Time Management",
        event_description: "Seminar on effective time management skills",
        event_date: new Date("2023-08-28"),
        event_category: "Seminar",
        user_id: 2,
    },
    {
        id: 44,
        event_name: "Dentist Appointment",
        event_description: "Dental check-up and cleaning",
        event_date: new Date("2023-08-05"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 45,
        event_name: "Exhibition: Art Showcase",
        event_description: "Exhibition featuring local artists' work",
        event_date: new Date("2023-08-18"),
        event_category: "Exhibition",
        user_id: 2,
    },
    {
        id: 46,
        event_name: "Team Building Activity",
        event_description: "Outdoor team-building event",
        event_date: new Date("2023-08-14"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 47,
        event_name: "Workshop: Yoga and Meditation",
        event_description: "Workshop focusing on relaxation techniques",
        event_date: new Date("2023-08-25"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 48,
        event_name: "Webinar: Marketing Trends",
        event_description: "Online webinar discussing current marketing trends",
        event_date: new Date("2023-08-30"),
        event_category: "Webinar",
        user_id: 2,
    },
    {
        id: 49,
        event_name: "Appointment with Therapist",
        event_description: "Private therapy session",
        event_date: new Date("2023-09-08"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 50,
        event_name: "Workshop: Public Speaking",
        event_description: "Learn effective public speaking techniques",
        event_date: new Date("2023-09-12"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 51,
        event_name: "Conference: Healthcare Summit",
        event_description: "Summit discussing advancements in healthcare",
        event_date: new Date("2023-09-20"),
        event_category: "Conference",
        user_id: 2,
    },
    {
        id: 52,
        event_name: "Work Shift: Night Shift",
        event_description: "Night shift for essential maintenance",
        event_date: new Date("2023-09-05"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 53,
        event_name: "Seminar: Financial Planning",
        event_description: "Seminar on managing personal finances",
        event_date: new Date("2023-09-18"),
        event_category: "Seminar",
        user_id: 2,
    },
    {
        id: 54,
        event_name: "Dentist Appointment",
        event_description: "Dental follow-up appointment",
        event_date: new Date("2023-09-10"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 55,
        event_name: "Exhibition: Sculpture Display",
        event_description: "Exhibition showcasing local sculptors",
        event_date: new Date("2023-09-25"),
        event_category: "Exhibition",
        user_id: 2,
    },
    {
        id: 56,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to review goals",
        event_date: new Date("2023-09-15"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 57,
        event_name: "Workshop: Yoga and Meditation",
        event_description: "Workshop focusing on relaxation techniques",
        event_date: new Date("2023-09-28"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 58,
        event_name: "Webinar: Digital Marketing Strategies",
        event_description: "Online webinar on effective digital marketing",
        event_date: new Date("2023-09-30"),
        event_category: "Webinar",
        user_id: 2,
    },
    {
        id: 59,
        event_name: "Appointment: Legal Consultation",
        event_description: "Meeting with a lawyer for legal advice",
        event_date: new Date("2023-10-08"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 60,
        event_name: "Workshop: Creative Writing",
        event_description: "Workshop to enhance creative writing skills",
        event_date: new Date("2023-10-12"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 61,
        event_name: "Conference: Renewable Energy Summit",
        event_description: "Summit discussing advancements in renewable energy",
        event_date: new Date("2023-10-20"),
        event_category: "Conference",
        user_id: 2,
    },
    {
        id: 62,
        event_name: "Work Shift: Morning Shift",
        event_description: "Morning shift for routine maintenance",
        event_date: new Date("2023-10-05"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 63,
        event_name: "Seminar: Leadership Development",
        event_description: "Seminar on becoming an effective leader",
        event_date: new Date("2023-10-18"),
        event_category: "Seminar",
        user_id: 2,
    },
    {
        id: 64,
        event_name: "Haircut Appointment",
        event_description: "Scheduled haircut and styling",
        event_date: new Date("2023-10-10"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 65,
        event_name: "Exhibition: Photography Showcase",
        event_description: "Exhibition featuring local photographers' work",
        event_date: new Date("2023-10-25"),
        event_category: "Exhibition",
        user_id: 2,
    },
    {
        id: 66,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss progress",
        event_date: new Date("2023-10-15"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 67,
        event_name: "Workshop: Painting Techniques",
        event_description: "Workshop teaching various painting techniques",
        event_date: new Date("2023-10-28"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 68,
        event_name: "Webinar: E-Commerce Strategies",
        event_description: "Online webinar on effective e-commerce strategies",
        event_date: new Date("2023-10-30"),
        event_category: "Webinar",
        user_id: 2,
    },
    {
        id: 69,
        event_name: "Appointment: Financial Advisor",
        event_description: "Meeting with a financial advisor",
        event_date: new Date("2023-11-08"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 70,
        event_name: "Workshop: Coding Bootcamp",
        event_description: "Intensive coding bootcamp for beginners",
        event_date: new Date("2023-11-12"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 71,
        event_name: "Conference: AI and Automation Summit",
        event_description: "Summit discussing AI and automation trends",
        event_date: new Date("2023-11-20"),
        event_category: "Conference",
        user_id: 2,
    },
    {
        id: 72,
        event_name: "Work Shift: Afternoon Shift",
        event_description: "Afternoon shift for system updates",
        event_date: new Date("2023-11-05"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 73,
        event_name: "Seminar: Stress Management",
        event_description: "Seminar on coping with stress effectively",
        event_date: new Date("2023-11-18"),
        event_category: "Seminar",
        user_id: 2,
    },
    {
        id: 74,
        event_name: "Eye Check-up Appointment",
        event_description: "Routine eye check-up and prescription update",
        event_date: new Date("2023-11-10"),
        event_category: "Appointment",
        user_id: 2,
    },
    {
        id: 75,
        event_name: "Exhibition: Modern Art Display",
        event_description: "Exhibition featuring contemporary artists' work",
        event_date: new Date("2023-11-25"),
        event_category: "Exhibition",
        user_id: 2,
    },
    {
        id: 76,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting for project planning",
        event_date: new Date("2023-11-15"),
        event_category: "Work Shift",
        user_id: 2,
    },
    {
        id: 77,
        event_name: "Workshop: Graphic Design Basics",
        event_description: "Workshop teaching fundamental graphic design techniques",
        event_date: new Date("2023-11-27"),
        event_category: "Workshop",
        user_id: 2,
    },
    {
        id: 78,
        event_name: "Webinar: E-Commerce Strategies",
        event_description: "Online webinar on effective e-commerce strategies",
        event_date: new Date("2023-11-30"),
        event_category: "Webinar",
        user_id: 2,
    },
    {
        id: 79,
        event_name: "Doctor's Appointment",
        event_description: "Regular check-up with the physician",
        event_date: new Date("2023-08-05"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 80,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss project updates",
        event_date: new Date("2023-08-10"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 81,
        event_name: "Conference: Tech Expo",
        event_description: "Tech expo showcasing the latest innovations",
        event_date: new Date("2023-08-15"),
        event_category: "Conference",
        user_id: 3,
    },
    {
        id: 82,
        event_name: "Workshop: Photography Basics",
        event_description: "Learn the basics of photography techniques",
        event_date: new Date("2023-08-20"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 83,
        event_name: "Seminar: Time Management",
        event_description: "Seminar on effective time management skills",
        event_date: new Date("2023-08-25"),
        event_category: "Seminar",
        user_id: 3,
    },
    {
        id: 84,
        event_name: "Dentist Appointment",
        event_description: "Dental check-up and cleaning",
        event_date: new Date("2023-08-07"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 85,
        event_name: "Exhibition: Art Showcase",
        event_description: "Exhibition featuring local artists' work",
        event_date: new Date("2023-08-12"),
        event_category: "Exhibition",
        user_id: 3,
    },
    {
        id: 86,
        event_name: "Team Building Activity",
        event_description: "Outdoor team-building event",
        event_date: new Date("2023-08-17"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 87,
        event_name: "Workshop: Yoga and Meditation",
        event_description: "Workshop focusing on relaxation techniques",
        event_date: new Date("2023-08-22"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 88,
        event_name: "Webinar: Marketing Trends",
        event_description: "Online webinar discussing current marketing trends",
        event_date: new Date("2023-08-30"),
        event_category: "Webinar",
        user_id: 3,
    },
    {
        id: 89,
        event_name: "Appointment with Therapist",
        event_description: "Private therapy session",
        event_date: new Date("2023-09-08"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 90,
        event_name: "Workshop: Public Speaking",
        event_description: "Learn effective public speaking techniques",
        event_date: new Date("2023-09-12"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 91,
        event_name: "Conference: Tech Summit",
        event_description: "Summit discussing the latest tech innovations",
        event_date: new Date("2023-09-18"),
        event_category: "Conference",
        user_id: 3,
    },
    {
        id: 92,
        event_name: "Work Shift: Night Shift",
        event_description: "Night shift for essential maintenance",
        event_date: new Date("2023-09-05"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 93,
        event_name: "Seminar: Financial Planning",
        event_description: "Seminar on managing personal finances",
        event_date: new Date("2023-09-22"),
        event_category: "Seminar",
        user_id: 3,
    },
    {
        id: 94,
        event_name: "Dentist Appointment",
        event_description: "Dental follow-up appointment",
        event_date: new Date("2023-09-10"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 95,
        event_name: "Exhibition: Art Showcase",
        event_description: "Exhibition featuring local artists' work",
        event_date: new Date("2023-09-26"),
        event_category: "Exhibition",
        user_id: 3,
    },
    {
        id: 96,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to review goals",
        event_date: new Date("2023-09-15"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 97,
        event_name: "Workshop: Yoga and Meditation",
        event_description: "Workshop focusing on relaxation techniques",
        event_date: new Date("2023-09-28"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 98,
        event_name: "Webinar: Digital Marketing Strategies",
        event_description: "Online webinar on effective digital marketing",
        event_date: new Date("2023-09-30"),
        event_category: "Webinar",
        user_id: 3,
    },
    {
        id: 99,
        event_name: "Appointment: Legal Consultation",
        event_description: "Meeting with a lawyer for legal advice",
        event_date: new Date("2023-10-08"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 100,
        event_name: "Workshop: Creative Writing",
        event_description: "Workshop to enhance creative writing skills",
        event_date: new Date("2023-10-12"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 101,
        event_name: "Conference: Tech Conference",
        event_description: "Tech conference discussing industry trends",
        event_date: new Date("2023-10-18"),
        event_category: "Conference",
        user_id: 3,
    },
    {
        id: 102,
        event_name: "Work Shift: Morning Shift",
        event_description: "Morning shift for routine maintenance",
        event_date: new Date("2023-10-05"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 103,
        event_name: "Seminar: Leadership Development",
        event_description: "Seminar on becoming an effective leader",
        event_date: new Date("2023-10-22"),
        event_category: "Seminar",
        user_id: 3,
    },
    {
        id: 104,
        event_name: "Haircut Appointment",
        event_description: "Scheduled haircut and styling",
        event_date: new Date("2023-10-10"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 105,
        event_name: "Exhibition: Art Gallery Opening",
        event_description: "Grand opening of a new art gallery",
        event_date: new Date("2023-10-28"),
        event_category: "Exhibition",
        user_id: 3,
    },
    {
        id: 106,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting for project planning",
        event_date: new Date("2023-10-15"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 107,
        event_name: "Workshop: Painting Techniques",
        event_description: "Workshop teaching various painting techniques",
        event_date: new Date("2023-10-29"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 108,
        event_name: "Webinar: E-Commerce Strategies",
        event_description: "Online webinar on effective e-commerce strategies",
        event_date: new Date("2023-10-31"),
        event_category: "Webinar",
        user_id: 3,
    },
    {
        id: 109,
        event_name: "Appointment: Financial Advisor",
        event_description: "Meeting with a financial advisor",
        event_date: new Date("2023-11-08"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 110,
        event_name: "Workshop: Coding Bootcamp",
        event_description: "Intensive coding bootcamp for beginners",
        event_date: new Date("2023-11-12"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 111,
        event_name: "Conference: Tech Summit",
        event_description: "Tech summit discussing future trends",
        event_date: new Date("2023-11-18"),
        event_category: "Conference",
        user_id: 3,
    },
    {
        id: 112,
        event_name: "Work Shift: Night Shift",
        event_description: "Night shift for essential maintenance",
        event_date: new Date("2023-11-05"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 113,
        event_name: "Seminar: Stress Management",
        event_description: "Seminar on coping with stress effectively",
        event_date: new Date("2023-11-22"),
        event_category: "Seminar",
        user_id: 3,
    },
    {
        id: 114,
        event_name: "Eye Check-up Appointment",
        event_description: "Routine eye check-up and prescription update",
        event_date: new Date("2023-11-10"),
        event_category: "Appointment",
        user_id: 3,
    },
    {
        id: 115,
        event_name: "Exhibition: Art Gallery Opening",
        event_description: "Opening of a new art gallery featuring local artists",
        event_date: new Date("2023-11-26"),
        event_category: "Exhibition",
        user_id: 3,
    },
    {
        id: 116,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss progress",
        event_date: new Date("2023-11-15"),
        event_category: "Work Shift",
        user_id: 3,
    },
    {
        id: 117,
        event_name: "Workshop: Graphic Design Basics",
        event_description: "Workshop teaching fundamental graphic design techniques",
        event_date: new Date("2023-11-27"),
        event_category: "Workshop",
        user_id: 3,
    },
    {
        id: 118,
        event_name: "Webinar: E-Commerce Strategies",
        event_description: "Online webinar on effective e-commerce strategies",
        event_date: new Date("2023-11-30"),
        event_category: "Webinar",
        user_id: 3,
    },
    {
        id: 119,
        event_name: "Workshop: Digital Marketing Trends",
        event_description: "In-person workshop on the latest digital marketing trends",
        event_date: new Date("2023-09-05"),
        event_category: "Workshop",
        user_id: 4,
      },
      {
        id: 120,
        event_name: "Fitness Class: HIIT Workout",
        event_description: "High-Intensity Interval Training (HIIT) fitness class",
        event_date: new Date("2023-09-08"),
        event_category: "Fitness",
        user_id: 4,
      },
      {
        id: 121,
        event_name: "Art Exhibition: Modern Art Showcase",
        event_description: "Exhibition featuring modern art from local artists",
        event_date: new Date("2023-09-12"),
        event_category: "Art",
        user_id: 4,
      },
      {
        id: 122,
        event_name: "Cooking Class: Italian Cuisine",
        event_description: "Hands-on cooking class to learn Italian recipes",
        event_date: new Date("2023-09-15"),
        event_category: "Cooking",
        user_id: 4,
      },
      {
        id: 123,
        event_name: "Music Concert: Jazz Night",
        event_description: "Live jazz music performance by renowned artists",
        event_date: new Date("2023-09-20"),
        event_category: "Music",
        user_id: 4,
      },
      {
        id: 124,
        event_name: "Business Seminar: Entrepreneurship 101",
        event_description: "Seminar for aspiring entrepreneurs to learn the basics",
        event_date: new Date("2023-09-23"),
        event_category: "Business",
        user_id: 4,
      },
      {
        id: 125,
        event_name: "Movie Night: Classic Film Screening",
        event_description: "Screening of a classic movie followed by discussions",
        event_date: new Date("2023-09-26"),
        event_category: "Entertainment",
        user_id: 4,
      },
      {
        id: 126,
        event_name: "Science Talk: Space Exploration",
        event_description: "Informative talk on the latest developments in space exploration",
        event_date: new Date("2023-09-29"),
        event_category: "Science",
        user_id: 4,
      },
      {
        id: 127,
        event_name: "Charity Fundraiser: Children's Education",
        event_description: "Fundraiser to support children's education initiatives",
        event_date: new Date("2023-09-17"),
        event_category: "Charity",
        user_id: 4,
      },
      {
        id: 128,
        event_name: "Educational Workshop: Coding for Beginners",
        event_description: "Workshop for beginners to learn coding fundamentals",
        event_date: new Date("2023-09-10"),
        event_category: "Education",
        user_id: 4,
      },
      {
        id: 129,
        event_name: "Tech Conference: AI and Machine Learning",
        event_description: "Conference exploring the latest in AI and machine learning",
        event_date: new Date("2023-09-05"),
        event_category: "Tech",
        user_id: 5,
      },
      {
        id: 130,
        event_name: "Cooking Class: Sushi Making",
        event_description: "Hands-on sushi-making class with a professional chef",
        event_date: new Date("2023-09-08"),
        event_category: "Cooking",
        user_id: 5,
      },
      {
        id: 131,
        event_name: "Art Exhibition: Contemporary Art Showcase",
        event_description: "Exhibition featuring contemporary art from local artists",
        event_date: new Date("2023-09-12"),
        event_category: "Art",
        user_id: 5,
      },
      {
        id: 132,
        event_name: "Fitness Workshop: Yoga and Meditation",
        event_description: "Workshop on yoga and meditation for physical and mental well-being",
        event_date: new Date("2023-09-15"),
        event_category: "Fitness",
        user_id: 5,
      },
      {
        id: 133,
        event_name: "Music Concert: Jazz Night",
        event_description: "Live jazz music performance by renowned artists",
        event_date: new Date("2023-09-18"),
        event_category: "Music",
        user_id: 5,
      },
      {
        id: 134,
        event_name: "Film Screening: Indie Film Festival",
        event_description: "Screening of independent films from emerging directors",
        event_date: new Date("2023-09-22"),
        event_category: "Film",
        user_id: 5,
      },
      {
        id: 135,
        event_name: "Charity Gala: Fundraising Dinner",
        event_description: "Gala dinner to raise funds for a charitable cause",
        event_date: new Date("2023-09-25"),
        event_category: "Charity",
        user_id: 5,
      },
      {
        id: 136,
        event_name: "Tech Workshop: Web Development Bootcamp",
        event_description: "Intensive web development workshop for beginners",
        event_date: new Date("2023-09-29"),
        event_category: "Tech",
        user_id: 5,
      },
      {
        id: 137,
        event_name: "Business Seminar: Entrepreneurship Masterclass",
        event_description: "Seminar on entrepreneurship and building successful startups",
        event_date: new Date("2023-09-02"),
        event_category: "Business",
        user_id: 5,
      },
      {
        id: 138,
        event_name: "Fashion Show: Fall Collection Premiere",
        event_description: "Fashion show featuring the latest fall clothing collection",
        event_date: new Date("2023-09-06"),
        event_category: "Fashion",
        user_id: 5,
      }
];