module.exports = [
    {
        id: 1,
        event_name: "Doctor's Appointment",
        event_description: "Regular check-up with the physician",
        event_date: new Date("2023-08-07"),
        event_category: "Appointment",
    },
    {
        id: 2,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss project updates",
        event_date: new Date("2023-08-15"),
        event_category: "Work Shift",
    },
    {
        id: 3,
        event_name: "Conference: Tech Expo",
        event_description: "Tech expo showcasing the latest innovations",
        event_date: new Date("2023-08-22"),
        event_category: "Conference",
    },
    {
        id: 4,
        event_name: "Workshop: Photography Basics",
        event_description: "Learn the basics of photography techniques",
        event_date: new Date("2023-08-10"),
        event_category: "Workshop",
    },
    {
        id: 5,
        event_name: "Seminar: Time Management",
        event_description: "Seminar on effective time management skills",
        event_date: new Date("2023-08-28"),
        event_category: "Seminar",
    },
    {
        id: 6,
        event_name: "Dentist Appointment",
        event_description: "Dental check-up and cleaning",
        event_date: new Date("2023-08-05"),
        event_category: "Appointment",
    },
    {
        id: 7,
        event_name: "Exhibition: Art Showcase",
        event_description: "Exhibition featuring local artists' work",
        event_date: new Date("2023-08-18"),
        event_category: "Exhibition",
    },
    {
        id: 8,
        event_name: "Team Building Activity",
        event_description: "Outdoor team-building event",
        event_date: new Date("2023-08-14"),
        event_category: "Work Shift",
    },
    {
        id: 9,
        event_name: "Workshop: Cooking Class",
        event_description: "Hands-on cooking class for beginners",
        event_date: new Date("2023-08-25"),
        event_category: "Workshop",
    },
    {
        id: 10,
        event_name: "Webinar: Marketing Trends",
        event_description: "Online webinar discussing current marketing trends",
        event_date: new Date("2023-08-30"),
        event_category: "Webinar",
    },
    {
        id: 11,
        event_name: "Appointment with Therapist",
        event_description: "Private therapy session.",
        event_date: new Date("2023-09-08"),
        event_category: "Appointment",
    },
    {
        id: 12,
        event_name: "Workshop: Public Speaking",
        event_description: "Learn effective public speaking techniques",
        event_date: new Date("2023-09-12"),
        event_category: "Workshop",
    },
    {
        id: 13,
        event_name: "Conference: Healthcare Summit",
        event_description: "Summit discussing advancements in healthcare",
        event_date: new Date("2023-09-20"),
        event_category: "Conference",
    },
    {
        id: 14,
        event_name: "Work Shift: Night Shift",
        event_description: "Night shift for essential maintenance",
        event_date: new Date("2023-09-05"),
        event_category: "Work Shift",
    },
    {
        id: 15,
        event_name: "Seminar: Financial Planning",
        event_description: "Seminar on managing personal finances",
        event_date: new Date("2023-09-18"),
        event_category: "Seminar",
    },
    {
        id: 16,
        event_name: "Dentist Appointment",
        event_description: "Dental follow-up appointment",
        event_date: new Date("2023-09-10"),
        event_category: "Appointment",
    },
    {
        id: 17,
        event_name: "Exhibition: Sculpture Display",
        event_description: "Exhibition showcasing local sculptors",
        event_date: new Date("2023-09-25"),
        event_category: "Exhibition",
    },
    {
        id: 18,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to review goals",
        event_date: new Date("2023-09-15"),
        event_category: "Work Shift",
    },
    {
        id: 19,
        event_name: "Yoga and Meditation",
        event_description: "Workshop focusing on relaxation techniques",
        event_date: new Date("2023-09-28"),
        event_category: "Workshop",
    },
    {
        id: 20,
        event_name: "Webinar: Digital Marketing Strategies",
        event_description: "Online webinar on effective digital marketing",
        event_date: new Date("2023-09-30"),
        event_category: "Webinar",
    },
    {
        id: 21,
        event_name: "Workshop: Creative Writing",
        event_description: "Workshop to enhance creative writing skills",
        event_date: new Date("2023-10-12"),
        event_category: "Workshop",
    },
    {
        id: 22,
        event_name: "Conference: Renewable Energy Summit",
        event_description: "Summit discussing advancements in renewable energy",
        event_date: new Date("2023-10-20"),
        event_category: "Conference",
    },
    {
        id: 23,
        event_name: "Work Shift: Morning Shift",
        event_description: "Morning shift for routine maintenance",
        event_date: new Date("2023-10-05"),
        event_category: "Work Shift",
    },
    {
        id: 24,
        event_name: "Leadership Development",
        event_description: "Seminar on becoming an effective leader",
        event_date: new Date("2023-10-18"),
        event_category: "Seminar",
    },
    {
        id: 25,
        event_name: "Haircut Appointment",
        event_description: "Scheduled haircut and styling",
        event_date: new Date("2023-10-10"),
        event_category: "Appointment",
    },
    {
        id: 26,
        event_name: "Exhibition: Photography Showcase",
        event_description: "Exhibition featuring local photographers' work",
        event_date: new Date("2023-10-25"),
        event_category: "Exhibition",
    },
    {
        id: 27,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting to discuss progress",
        event_date: new Date("2023-10-15"),
        event_category: "Work Shift",
    },
    {
        id: 28,
        event_name: "Workshop: Painting Techniques",
        event_description: "Workshop teaching various painting techniques",
        event_date: new Date("2023-10-28"),
        event_category: "Workshop",
    },
    {
        id: 29,
        event_name: "Webinar: E-Commerce Strategies",
        event_description: "Online webinar on effective e-commerce strategies",
        event_date: new Date("2023-10-30"),
        event_category: "Webinar",
    },
    {
        id: 30,
        event_name: "Appointment: Financial Advisor",
        event_description: "Meeting with a financial advisor",
        event_date: new Date("2023-11-08"),
        event_category: "Appointment",
    },
    {
        id: 31,
        event_name: "Workshop: Coding Bootcamp",
        event_description: "Intensive coding bootcamp for beginners",
        event_date: new Date("2023-11-12"),
        event_category: "Workshop",
    },
    {
        id: 32,
        event_name: "Conference: AI and Automation Summit",
        event_description: "Summit discussing AI and automation trends",
        event_date: new Date("2023-11-20"),
        event_category: "Conference",
    },
    {
        id: 33,
        event_name: "Work Shift: Afternoon Shift",
        event_description: "Afternoon shift for system updates",
        event_date: new Date("2023-11-05"),
        event_category: "Work Shift",
    },
    {
        id: 34,
        event_name: "Seminar: Stress Management",
        event_description: "Seminar on coping with stress effectively",
        event_date: new Date("2023-11-18"),
        event_category: "Seminar",
    },
    {
        id: 35,
        event_name: "Eye Check-up Appointment",
        event_description: "Routine eye check-up and prescription update",
        event_date: new Date(" 2023-11-10"),
        event_category: "Appointment",
    },
    {
        id: 36,
        event_name: "Exhibition: Modern Art Display",
        event_description: "Exhibition featuring contemporary artists' work",
        event_date: new Date("2023-11-25"),
        event_category: "Exhibition",
    },
    {
        id: 37,
        event_name: "Team Meeting",
        event_description: "Monthly team meeting for project planning",
        event_date: new Date("2023-11-15"),
        event_category: "Work Shift",
    },
    {
        id: 38,
        event_name: "Workshop: Graphic Design Basics",
        event_description: "Learn Graphic Design Basics",
        event_date: new Date("2023-11-19"),
        event_category: "Workshop",
    },
];