module.exports = [
    {
        id: 1,
        user_first_name: "Erika",
        user_last_name: "Regalado",
        user_birthday: "05/17/1995",
        user_city: "Toronto",
        user_description: "Hi there! I'm Erika, a passionate gamer who loves painting and capturing beautiful moments through photography. When I'm not gaming, you can find me on the football field or exploring the world of music. I'm also a proud member of the Foodie, League of Legends, Web Development, Rock Climbing, and Strava communities.",
        user_interests: JSON.stringify(["Gaming", "Painting", "Photography", "Football", "Music"]),
        user_groups: JSON.stringify(["Foodie", "League of Legends", "Web Development", "Rock Climbing", "Strava"]),
    },
    {
        id: 2,
        user_first_name: "Elaine",
        user_last_name: "Mendoza",
        user_birthday: "04/06/1997",
        user_city: "Toronto",
        user_description: "Hey, I'm Elaine! I have a love for basketball and a knack for interior design. In the winter, you'll find me shredding the slopes while snowboarding, and I'm a baking enthusiast in the kitchen. I'm part of the Gym, Winter Sports, Foodie, Pastry Chef, and Toronto communities.",
        user_interests: JSON.stringify(["Basketball", "Interior Design", "Snowboarding", "Baking"]),
        user_groups: JSON.stringify(["Gym", "Winter Sports", "Foodie", "Pastry Chef", "Toronto"]),
    },
    {
        id: 3,
        user_first_name: "Mike",
        user_last_name: "Piette",
        user_birthday: "01/30/2000",
        user_city: "Toronto",
        user_description: "Hello, I'm Mike! I'm a gaming enthusiast who also finds zen in yoga and spinning. I'm a skilled archer, too! Outside of my interests, I'm part of the Foodie, Rock Climbing, Muay Thai, and Urban Exploration communities.",
        user_interests: JSON.stringify(["Gaming", "Yoga", "Spinning", "Archery"]),
        user_groups: JSON.stringify(["Foodie", "Rock Climbing", "Muay Thai", "Urban Exploration"]),
    },
    {
        id: 4,
        user_first_name: "Sarah",
        user_last_name: "Anderson",
        user_birthday: "05/15/1995",
        user_city: "Mississauga",
        user_description: "Hey, I'm Sarah! I have a passion for photography, and I love experimenting in the kitchen while cooking up delicious meals. When I'm not behind the camera or in the kitchen, you can find me hiking or working on my next painting. I'm part of the Nature Lovers, Cooking Enthusiasts, and Art Club communities.",
        user_interests: JSON.stringify(["Photography", "Cooking", "Hiking", "Painting"]),
        user_groups: JSON.stringify(["Nature Lovers", "Cooking Enthusiasts", "Art Club"])
    },
    {
        id: 5,
        user_first_name: "Daniel",
        user_last_name: "Smith",
        user_birthday: "09/22/1988",
        user_city: "Brampton",
        user_description: "Hi, I'm Daniel! I'm an avid reader and a soccer fanatic. I enjoy peaceful days fishing by the lake and camping in the great outdoors. I'm part of the Bookworms, Sports Fans, and Outdoor Adventurers communities.",
        user_interests: JSON.stringify(["Reading", "Soccer", "Fishing", "Camping"]),
        user_groups: JSON.stringify(["Bookworms", "Sports Fans", "Outdoor Adventurers"])
    },
    {
        id: 6,
        user_first_name: "Emily",
        user_last_name: "Chen",
        user_birthday: "03/12/1992",
        user_city: "Oakville",
        user_description: "Hello there, I'm Emily! I find joy in dancing and exploring new places through travel. Meditation helps me stay grounded, and I'm quite the swimmer too. I'm a proud member of the Dance Enthusiasts, Wanderlust Explorers, and Mindfulness Club communities.",
        user_interests: JSON.stringify(["Dancing", "Traveling", "Meditation", "Swimming"]),
        user_groups: JSON.stringify(["Dance Enthusiasts", "Wanderlust Explorers", "Mindfulness Club"])
    },
    {
        id: 7,
        user_first_name: "Alex",
        user_last_name: "Garcia",
        user_birthday: "11/05/1987",
        user_city: "Markham",
        user_description: "Hi, I'm Alex! I'm passionate about golfing and enjoy experimenting with new recipes in the kitchen. I'm also a photography enthusiast and have a green thumb for gardening. I'm part of the Golfers, Culinary Creators, Shutterbugs, and Green Thumbs communities.",
        user_interests: JSON.stringify(["Golf", "Cooking", "Photography", "Gardening"]),
        user_groups: JSON.stringify(["Golfers", "Culinary Creators", "Shutterbugs", "Green Thumbs"])
    },
    {
        id: 8,
        user_first_name: "Olivia",
        user_last_name: "Martin",
        user_birthday: "07/18/1998",
        user_city: "Vaughan",
        user_description: "Hello, I'm Olivia! I find inspiration in painting and practicing yoga. I'm an outdoor enthusiast who loves hiking and a board game enthusiast in my downtime. I'm part of the Art Enthusiasts, Yogis, Outdoor Enthusiasts, and Board Gamers communities.",
        user_interests: JSON.stringify(["Painting", "Yoga", "Hiking", "Board Games"]),
        user_groups: JSON.stringify(["Art Enthusiasts", "Yogis", "Outdoor Enthusiasts", "Board Gamers"])
    },
    {
        id: 9,
        user_first_name: "Lucas",
        user_last_name: "Johnson",
        user_birthday: "12/09/1990",
        user_city: "Richmond Hill",
        user_description: "Hey there, I'm Lucas! I'm a basketball fan and a dedicated reader. My culinary explorations in the kitchen keep me busy, and I'm always up for new travel adventures. I'm part of the Hoops Fans, Book Club, Culinary Explorers, and Wanderlust communities.",
        user_interests: JSON.stringify(["Basketball", "Reading", "Cooking", "Travelling"]),
        user_groups: JSON.stringify(["Hoops Fans", "Book Club", "Culinary Explorers", "Wanderlust"])
    },
    {
        id: 10,
        user_first_name: "Ava",
        user_last_name: "Wilson",
        user_birthday: "04/25/1993",
        user_city: "Thornhill",
        user_description: "Hi, I'm Ava! I'm passionate about singing and cycling through scenic routes. I have a keen eye for photography, and I love exploring the underwater world through scuba diving. I'm part of the Singing Enthusiasts, Cyclists, Shutterbugs, and Scuba Divers communities.",
        user_interests: JSON.stringify(["Singing", "Cycling", "Photography", "Scuba Diving"]),
        user_groups: JSON.stringify(["Singing Enthusiasts", "Cyclists", "Shutterbugs", "Scuba Divers"])
    },
    {
        id: 11,
        user_first_name: "Liam",
        user_last_name: "Harris",
        user_birthday: "08/14/1985",
        user_city: "Scarborough",
        user_description: "Hello, I'm Liam! I'm a football fanatic and a gamer at heart. I enjoy cooking up culinary delights and hiking in the great outdoors. I'm part of the Football Fanatics, Gamers United, Culinary Artists, and Adventure Seekers communities.",
        user_interests: JSON.stringify(["Football", "Gaming", "Cooking", "Hiking"]),
        user_groups: JSON.stringify(["Football Fanatics", "Gamers United", "Culinary Artists", "Adventure Seekers"])
    },
    {
        id: 12,
        user_first_name: "Sophia",
        user_last_name: "Lee",
        user_birthday: "02/03/1996",
        user_city: "Pickering",
        user_description: "Hey, I'm Sophia! I express myself through dance and capture moments through photography. Yoga and meditation keep me balanced and mindful. I'm part of the Dance Lovers, Shutterbugs, Yogis, and Mindfulness Practitioners communities.",
         user_interests: JSON.stringify(["Dancing", "Photography", "Yoga", "Meditation"]),
        user_groups: JSON.stringify(["Dance Lovers", "Shutterbugs", "Yogis", "Mindfulness Practitioners"])
    },
    {
        id: 13,
        user_first_name: "Mason",
        user_last_name: "Brown",
        user_birthday: "06/20/1991",
        user_city: "Ajax",
        user_description: "Hi there, I'm Mason! I'm an avid golfer and soccer enthusiast. Cycling is another passion, and I enjoy relaxing days fishing by the water. I'm part of the Golf Enthusiasts, Soccer Fans, Cyclists Club, and Fishing Enthusiasts communities.",
        user_interests: JSON.stringify(["Golf", "Soccer", "Cycling", "Fishing"]),
        user_groups: JSON.stringify(["Golf Enthusiasts", "Soccer Fans", "Cyclists Club", "Fishing Enthusiasts"])
    },
]